### ISSUE TITLE
sdlpop fails to run with syntax error on launcher

### ISSUE THREAD

**Issue by DiogoConstantino** [snapcrafters/sdlpop#5]
diogo@Edwin:~$ snap install sdlpop
sdlpop v1.18.1 from Snapcrafters installed
diogo@Edwin:~$ sdlpop 
/snap/sdlpop/67/bin/desktop-launch: line 410: ((: /home/diogo/snap/sdlpop/67/.local/share/icons/*: syntax error: operand expected (error token is "/home/diogo/snap/sdlpop/67/.local/share/icons/*")
SDL_CreateTexture: Invalid renderer

**Comment by popey** [comment]
Thanks for reporting the issue. The latest revision in the stable channel should have fixed this. Please do let me know if not. Thanks!
