### ISSUE TITLE
sdlpop fails to run with sdl error on 16.04

### ISSUE THREAD

**Issue by DiogoConstantino** [snapcrafters/sdlpop#6]
In Ubuntu 16.04:

> diogo@Edwin:\~$ snap install sdlpop
sdlpop v1.18.1 from Snapcrafters installed
diogo@Edwin:\~$ sdlpop
SDL_CreateTexture: Invalid renderer
diogo@Edwin:~$

Works fine on 18.04.

**Comment by popey** [comment]
Thanks for the report. Can you please:-

`snap version`

And let me know what GPU and driver you're using?

**Comment by DiogoConstantino** [comment]
diogo@Edwin:~$ snap version
snap    2.35.5
snapd   2.35.5
series  16
ubuntu  16.04

The GPU:
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 950M] (rev a2)

The driver is the Nvidia version 384.130 provided via the Ubuntu additional drivers tool.

**Comment by DiogoConstantino** [comment]
I've just rebooted the system (I don't do this often). and now it's working properly.... Must try this more often...

**Comment by galgalesh** [comment]
I just tested it again on Ubuntu 16.04 and it seems to work without issues.

@popey, can you close this issue?

**Comment by popey** [comment]
Thanks @galgalesh
